## Data Manipulation module
### Homework assignment 2
Welcome to the second homework assignment of the data manipulation module. In this assignment you will be working with Pandas DataFrames. The goal of this assignment is to get you familiar with such dataframes in Python.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 25-01 23:59**.

In [124]:
import pandas as pd
import numpy as np

Download the `weatherAUS.csv` file from the following [kaggle page](https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package). We load it in in the following cell, make sure to set the correct path. The rest of the assignment you will be using this dataframe!

In [125]:
df = pd.read_csv('weatherAUS.csv')
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

1. Use the describe function to gain insight in the attributes of the dataframe. Analyze the info and create a short write-up according to your findings.

In [147]:
df.describe(include='all')
# The data of Ausralia weather have information of Date	Location	MinTemp	MaxTemp	Rainfall	Evaporation	Sunshine	WindGustDir	WindGustSpeed
# 	WindDir9am	WindDir3pm	WindSpeed9am	WindSpeed3pm	Humidity9am	Humidity3pm	Pressure9am	Pressure3pm	Cloud9am	Cloud3pm	Temp9am	
# Temp3pm	RainToday	RainTomorrow
# there are 47 different locations
# The minimum temprature is -8.5 and the maximum temprature is 48.10
# The average minimum temprature is: 12.144036 and the average maximum temprature is: 23.287516

,date,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,tempdiff
count,135134,135134,134396.000000,134572.000000,132474.000000,77618.000000,71087.000000,135134,135134.000000,127519,...,132759.000000,124354.000000,124395.000000,81552.000000,79492.000000,134045.000000,133587.000000,132474,132863,134336.000000
unique,3434,47,NaN,NaN,NaN,NaN,NaN,16,NaN,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN
top,08/12/13,Perth,NaN,NaN,NaN,NaN,NaN,W,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NoRain,NoRain,NaN
freq,47,3188,NaN,NaN,NaN,NaN,NaN,9915,NaN,11256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103126,103453,NaN
mean,NaN,NaN,12.144036,23.287516,2.329065,5.514989,7.648307,NaN,40.035106,NaN,...,51.120813,1017.628408,1015.220109,4.437083,4.510139,16.985706,21.741268,NaN,NaN,11.145525
std,NaN,NaN,6.462347,7.201843,8.402218,4.220401,3.787404,NaN,13.607080,NaN,...,20.866908,7.100802,7.030968,2.888186,2.722881,6.565138,7.007074,NaN,NaN,4.965668
min,NaN,NaN,-8.500000,-4.800000,0.000000,0.000000,0.000000,NaN,6.000000,NaN,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,NaN,NaN,0.000000
25%,NaN,NaN,7.500000,17.900000,0.000000,2.600000,4.900000,NaN,31.000000,NaN,...,36.000000,1012.900000,1010.400000,1.000000,2.000000,12.200000,16.600000,NaN,NaN,7.300000
50%,NaN,NaN,11.900000,22.800000,0.000000,4.800000,8.500000,NaN,39.000000,NaN,...,51.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.200000,NaN,NaN,10.600000
75%,NaN,NaN,16.800000,28.400000,0.600000,7.400000,10.700000,NaN,48.000000,NaN,...,65.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.600000,NaN,NaN,14.600000
max,NaN,NaN,33.900000,48.100000,367.600000,86.200000,14.500000,NaN,135.000000,NaN,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,NaN,NaN,31.200000

YOUR ANSWER HERE

2. Find the shape and the size of the dataset

In [127]:
df.shape
df.size

3345580

3. Find the types of all columns and save the result as a dataframe with the column names as index. Call the column with the types 'dtypes'.

In [128]:
types_df = pd.DataFrame(df.dtypes, columns=['dtypes'])

print(types_df)

                dtypes
Date            object
Location        object
MinTemp        float64
MaxTemp        float64
Rainfall       float64
Evaporation    float64
Sunshine       float64
WindGustDir     object
WindGustSpeed  float64
WindDir9am      object
WindDir3pm      object
WindSpeed9am   float64
WindSpeed3pm   float64
Humidity9am    float64
Humidity3pm    float64
Pressure9am    float64
Pressure3pm    float64
Cloud9am       float64
Cloud3pm       float64
Temp9am        float64
Temp3pm        float64
RainToday       object
RainTomorrow    object

4. Find the non-null counts of all columns and save the result as a dataframe with the column names as index. Call the column with the non-null counts 'counts'.

In [129]:
counts = df.count()
counts_df = pd.DataFrame(counts, columns=['counts'])
print(counts_df.shape)
print(counts_df)

(23, 1)
               counts
Date           145460
Location       145460
MinTemp        143975
MaxTemp        144199
Rainfall       142199
Evaporation     82670
Sunshine        75625
WindGustDir    135134
WindGustSpeed  135197
WindDir9am     134894
WindDir3pm     141232
WindSpeed9am   143693
WindSpeed3pm   142398
Humidity9am    142806
Humidity3pm    140953
Pressure9am    130395
Pressure3pm    130432
Cloud9am        89572
Cloud3pm        86102
Temp9am        143693
Temp3pm        141851
RainToday      142199
RainTomorrow   142193

5. Find the null counts of all columns and save the result as a dataframe with the column names as index. Call the column with the null counts 'null-counts'.

In [130]:
null_counts = df.isnull().sum()
null_counts_df = pd.DataFrame (null_counts, columns=["null_counts"])
print(null_counts_df)

               null_counts
Date                     0
Location                 0
MinTemp               1485
MaxTemp               1261
Rainfall              3261
Evaporation          62790
Sunshine             69835
WindGustDir          10326
WindGustSpeed        10263
WindDir9am           10566
WindDir3pm            4228
WindSpeed9am          1767
WindSpeed3pm          3062
Humidity9am           2654
Humidity3pm           4507
Pressure9am          15065
Pressure3pm          15028
Cloud9am             55888
Cloud3pm             59358
Temp9am               1767
Temp3pm               3609
RainToday             3261
RainTomorrow          3267

6. Find the number of unique values of all columns and save the result as a dataframe with the column names as index. Call the column with the unique counts 'unique-counts'.

In [131]:
unique_counts = df.nunique()
unique_counts_df = pd.DataFrame (unique_counts, columns= ["unique-counts"])
print(unique_counts_df)

               unique-counts
Date                    3436
Location                  49
MinTemp                  389
MaxTemp                  505
Rainfall                 681
Evaporation              358
Sunshine                 145
WindGustDir               16
WindGustSpeed             67
WindDir9am                16
WindDir3pm                16
WindSpeed9am              43
WindSpeed3pm              44
Humidity9am              101
Humidity3pm              101
Pressure9am              546
Pressure3pm              549
Cloud9am                  10
Cloud3pm                  10
Temp9am                  441
Temp3pm                  502
RainToday                  2
RainTomorrow               2

7. Merge the dataframes you created exercise 3, 4, 5 and 6 into one dataframe with the column names as index and the columns 'dtypes', 'counts', 'null-counts' and 'unique-counts'.

In [132]:
#result = pd.merge(types_df, counts_df,null_counts_df)
merged = pd.concat ([types_df, counts_df,null_counts_df,unique_counts_df], axis=0)
print(merged)

               dtypes  counts  null_counts  unique-counts
Date           object     NaN          NaN            NaN
Location       object     NaN          NaN            NaN
MinTemp       float64     NaN          NaN            NaN
MaxTemp       float64     NaN          NaN            NaN
Rainfall      float64     NaN          NaN            NaN
...               ...     ...          ...            ...
Cloud3pm          NaN     NaN          NaN           10.0
Temp9am           NaN     NaN          NaN          441.0
Temp3pm           NaN     NaN          NaN          502.0
RainToday         NaN     NaN          NaN            2.0
RainTomorrow      NaN     NaN          NaN            2.0

[92 rows x 4 columns]

8. Lowercase all column names of the dataframe.

In [133]:
df.columns = df.columns.str.lower()
print(df)

              date location  mintemp  maxtemp  rainfall  evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN
1       2008-12-02   Albury      7.4     25.1       0.0          NaN
2       2008-12-03   Albury     12.9     25.7       0.0          NaN
3       2008-12-04   Albury      9.2     28.0       0.0          NaN
4       2008-12-05   Albury     17.5     32.3       1.0          NaN
...            ...      ...      ...      ...       ...          ...
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN

        sunshine windgustdir  windgustspeed winddir9am  ... humidity9am  \
0            NaN           W           44.0          W  ...        71.0
1            NaN         WNW           44.0        NNW  ...        44.0
2            NaN         WSW           46.0          W  ...        38.0
3            NaN          NE           24.0         SE  ...        45.0
4            NaN           W           41.0        ENE  ...        82.0
...          ...         ...            ...        ...  ...         ...
145455       NaN           E           31.0         SE  ...        51.0
145456       NaN         NNW           22.0         SE  ...        56.0
145457       NaN           N           37.0         SE  ...        53.0
145458       NaN          SE           28.0        SSE  ...        51.0
145459       NaN         NaN            NaN        ESE  ...        62.0

        humidity3pm  pressure9am  pressure3pm  cloud9am  cloud3pm  temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9
1              25.0       1010.6       1007.8       NaN       NaN     17.2
2              30.0       1007.6       1008.7       NaN       2.0     21.0
3              16.0       1017.6       1012.8       NaN       NaN     18.1
4              33.0       1010.8       1006.0       7.0       8.0     17.8
...             ...          ...          ...       ...       ...      ...
145455         24.0       1024.6       1020.3       NaN       NaN     10.1
145456         21.0       1023.5       1019.1       NaN       NaN     10.9
145457         24.0       1021.0       1016.8       NaN       NaN     12.5
145458         24.0       1019.4       1016.5       3.0       2.0     15.1
145459         36.0       1020.2       1017.9       8.0       8.0     15.0

        temp3pm  raintoday  raintomorrow
0          21.8         No            No
1          24.3         No            No
2          23.2         No            No
3          26.5         No            No
4          29.7         No            No
...         ...        ...           ...
145455     22.4         No            No
145456     24.5         No            No
145457     26.1         No            No
145458     26.0         No            No
145459     20.9         No           NaN

[145460 rows x 23 columns]

9. Change all the "No" strings to "NoRain" and all the "Yes" strings to "Rain" in the raintoday and raintomorrow column.

In [134]:
df['raintoday'] = df['raintoday'].replace({'No': 'NoRain', 'Yes': 'Rain'})
df['raintomorrow'] = df['raintomorrow'].replace({'No': 'NoRain', 'Yes': 'Rain'})

10. Change the datatype of the "date" column to datetime64 and reformat the date as DD/MM/YYYY.
Hint: use `to_datetime` and `strftime`.

In [135]:
df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime('%d/%m/%y')

11. Create a new column with the difference between the maxtemp and mintemp columns for each row. Call this column tempdiff.

In [136]:
df['tempdiff'] = df.maxtemp - df.mintemp
df

,date,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,tempdiff
0,01/12/08,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,NoRain,NoRain,9.5
1,02/12/08,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,NoRain,NoRain,17.7
2,03/12/08,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,NoRain,NoRain,12.8
3,04/12/08,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,NoRain,NoRain,18.8
4,05/12/08,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,NoRain,NoRain,14.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,21/06/17,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,NoRain,NoRain,20.6
145456,22/06/17,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,NoRain,NoRain,21.7
145457,23/06/17,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,NoRain,NoRain,21.5
145458,24/06/17,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,NoRain,NoRain,19.2
145459,25/06/17,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,NoRain,NaN,NaN

12. Remove the evaporation and sunshine columns from the dataframe.

In [137]:
df.drop(['evaporation', 'sunshine'], axis=1)

,date,location,mintemp,maxtemp,rainfall,windgustdir,windgustspeed,winddir9am,winddir3pm,windspeed9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,tempdiff
0,01/12/08,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,NoRain,NoRain,9.5
1,02/12/08,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,NoRain,NoRain,17.7
2,03/12/08,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,NoRain,NoRain,12.8
3,04/12/08,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,NoRain,NoRain,18.8
4,05/12/08,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,NoRain,NoRain,14.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,21/06/17,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,NoRain,NoRain,20.6
145456,22/06/17,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,NoRain,NoRain,21.7
145457,23/06/17,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,NoRain,NoRain,21.5
145458,24/06/17,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,NoRain,NoRain,19.2
145459,25/06/17,Uluru,14.9,NaN,0.0,NaN,NaN,ESE,ESE,17.0,...,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,NoRain,NaN,NaN

13. Find the most rainy day for each city

In [138]:
i_rainy = df.groupby('location')['rainfall'].idxmax()
most_rainy_day = df.loc[i_rainy]
most_rainy_day

,date,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,tempdiff
98285,14/02/14,Adelaide,20.6,24.5,75.2,NaN,0.0,NE,26.0,NE,...,86.0,1003.2,998.8,NaN,NaN,22.0,23.2,Rain,Rain,3.9
109820,02/06/12,Albany,13.0,20.7,49.4,NaN,7.5,NaN,NaN,ENE,...,55.0,1022.3,1021.3,7.0,5.0,15.8,19.9,Rain,NoRain,7.7
1156,01/03/12,Albury,17.1,20.9,104.2,NaN,NaN,SE,57.0,N,...,88.0,1002.0,1001.9,8.0,8.0,19.5,18.5,Rain,Rain,3.8
136525,28/02/10,AliceSprings,18.8,19.8,62.0,3.4,0.0,SE,61.0,SE,...,95.0,1004.8,1003.2,8.0,8.0,18.9,19.3,Rain,Rain,1.0
4468,29/01/13,BadgerysCreek,18.3,28.1,116.0,NaN,NaN,WSW,37.0,W,...,75.0,1001.5,1004.4,NaN,NaN,22.3,24.9,Rain,NoRain,9.8
55876,14/01/11,Ballarat,15.8,25.5,95.0,NaN,NaN,NaN,NaN,WSW,...,69.0,1002.7,NaN,8.0,NaN,16.0,23.5,Rain,NaN,9.7
58938,05/02/11,Bendigo,20.7,21.3,66.4,9.0,NaN,N,50.0,W,...,94.0,1006.1,1007.0,8.0,8.0,21.2,17.3,Rain,Rain,0.6
86414,02/05/15,Brisbane,16.6,24.9,182.6,1.6,9.5,SSW,19.0,WNW,...,58.0,1013.0,1010.0,1.0,1.0,19.8,24.4,Rain,NoRain,8.3
87242,12/01/09,Cairns,22.3,27.4,278.4,NaN,0.0,NW,59.0,SSE,...,98.0,1003.5,999.6,8.0,8.0,24.7,25.3,Rain,Rain,5.1
46715,03/12/10,Canberra,13.4,22.4,87.0,NaN,3.1,W,39.0,S,...,76.0,1017.4,1014.5,7.0,7.0,16.1,20.1,Rain,Rain,9.0
7832,16/02/14,Cobar,21.4,28.6,68.0,NaN,NaN,SW,44.0,S,...,62.0,1002.6,1003.0,8.0,6.0,21.6,26.3,Rain,Rain,7.2
9368,07/11/09,CoffsHarbour,17.4,23.1,371.0,NaN,3.5,NaN,NaN,SW,...,81.0,1026.6,1025.9,8.0,5.0,18.6,22.0,Rain,Rain,5.7
81741,14/01/11,Dartmoor,16.2,24.4,73.6,NaN,8.2,W,44.0,NNW,...,64.0,1003.1,1003.8,NaN,NaN,17.4,23.2,Rain,NoRain,8.2
140071,16/02/11,Darwin,22.1,25.6,367.6,NaN,0.0,WSW,83.0,SSE,...,98.0,996.3,996.0,8.0,8.0,24.3,23.5,Rain,Rain,3.5
91455,29/04/12,GoldCoast,17.2,24.4,183.4,NaN,NaN,S,56.0,S,...,67.0,1014.2,1015.0,NaN,NaN,22.0,21.9,Rain,NoRain,7.2
132137,14/01/15,Hobart,17.0,19.3,71.6,NaN,0.0,SSW,61.0,SSE,...,90.0,991.9,991.2,7.0,8.0,18.4,17.9,Rain,Rain,2.3
143335,27/12/15,Katherine,22.5,26.5,167.0,NaN,NaN,W,52.0,WSW,...,NaN,1003.6,1002.9,8.0,NaN,25.0,NaN,Rain,Rain,4.0
135557,29/01/16,Launceston,17.2,23.6,88.0,NaN,NaN,SE,46.0,SSE,...,89.0,NaN,NaN,8.0,8.0,19.9,20.2,Rain,Rain,6.4
68151,07/02/11,Melbourne,10.8,21.5,82.2,4.6,12.7,S,37.0,WSW,...,45.0,1026.0,1024.2,3.0,1.0,15.0,20.2,Rain,Rain,10.7
65714,01/06/13,MelbourneAirport,12.8,15.1,75.8,8.0,0.0,S,31.0,N,...,90.0,1013.1,1011.1,8.0,7.0,13.2,14.9,Rain,Rain,2.3
71158,05/02/11,Mildura,22.9,23.2,155.0,NaN,1.6,N,28.0,WNW,...,97.0,1009.1,1009.4,8.0,8.0,23.2,19.4,Rain,Rain,0.3
13096,26/11/11,Moree,19.5,27.5,113.0,12.1,8.5,NW,39.0,WNW,...,58.0,1012.1,1009.4,7.0,6.0,21.5,26.0,Rain,NoRain,8.0
100287,14/01/11,MountGambier,15.8,23.1,84.6,NaN,8.2,W,41.0,NNW,...,67.0,1003.5,1004.7,8.0,4.0,16.9,21.8,Rain,NoRain,7.3
53221,04/03/12,MountGinini,5.8,14.8,107.6,NaN,NaN,N,72.0,NNW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rain,Rain,9.0
17321,23/04/15,Newcastle,NaN,21.7,240.0,NaN,NaN,NaN,NaN,NW,...,62.0,NaN,NaN,6.0,6.0,17.5,21.0,Rain,NoRain,NaN
73505,12/06/13,Nhil,10.1,11.9,65.6,NaN,NaN,SE,54.0,SE,...,91.0,1010.3,1008.2,NaN,NaN,10.8,10.9,Rain,Rain,1.8
19661,24/06/13,NorahHead,10.2,15.6,126.4,NaN,NaN,SE,46.0,SSW,...,76.0,1022.1,1017.5,NaN,NaN,10.7,14.2,Rain,NoRain,5.4
23667,22/03/16,NorfolkIsland,19.5,25.5,156.8,NaN,NaN,NE,31.0,NW,...,79.0,1005.6,1004.5,6.0,6.0,23.8,24.9,Rain,NoRain,6.0
103259,08/12/10,Nuriootpa,16.1,22.0,76.6,NaN,6.8,WSW,44.0,W,...,64.0,1005.0,1005.6,8.0,7.0,16.2,20.5,Rain,NoRain,5.9
115660,07/12/11,PearceRAAF,17.6,28.3,62.4,NaN,8.1,SSW,39.0,NE,...,50.0,1003.1,1001.1,4.0,5.0,22.8,25.3,Rain,NoRain,10.7
25263,10/02/12,Penrith,18.4,26.4,115.4,NaN,NaN,S,26.0,E,...,81.0,NaN,NaN,NaN,NaN,19.7,23.2,Rain,NoRain,8.0
123695,10/02/17,Perth,14.8,22.4,114.4,14.4,0.0,SE,41.0,SE,...,94.0,1007.5,1007.2,8.0,8.0,16.5,19.3,Rain,Rain,7.6
118185,11/07/10,PerthAirport,9.7,19.0,76.6,1.0,5.4,NW,63.0,N,...,60.0,1015.2,1010.9,7.0,7.0,12.2,18.3,Rain,NoRain,9.3
75723,14/01/11,Portland,15.6,20.6,72.0,NaN,8.2,NW,52.0,WNW,...,79.0,1002.3,1004.1,8.0,6.0,16.8,19.8,Rain,NoRain,5.0
29379,21/04/15,Richmond,12.6,16.1,113.4,NaN,NaN,SSW,50.0,SSW,...,88.0,1020.1,1018.6,8.0,7.0,13.4,13.5,Rain,Rain,3.5
63259,07/12/14,Sale,13.8,19.1,55.6,NaN,NaN,S,63.0,S,...,91.0,1008.7,1002.5,8.0,6.0,13.9,17.7,Rain,Rain,5.3
125255,02/03/13,SalmonGums,15.0,21.1,55.4,NaN,NaN,SE,39.0,ESE,...,80.0,NaN,NaN,NaN,NaN,17.6,20.4,Rain,NoRain,6.1
32723,21/04/15,Sydney,14.5,17.7,119.4,NaN,0.0,SSE,87.0,SSE,...,96.0,1019.6,1016.8,8.0,8.0,14.9,14.6,Rain,Rain,3.2
35544,15/10/14,SydneyAirport,9.9,16.4,106.8,NaN,0.1,SSW,102.0,SW,...,54.0,1011.9,1013.5,8.0,7.0,12.0,14.8,Rain,NoRain,6.5
93344,03/02/09,Townsville,22.8,25.4,236.8,NaN,0.0,ESE,48.0,ESE,...,95.0,1003.8,1000.6,8.0,8.0,23.8,25.0,Rain,Rain,2.6
49761,09/12/10,Tuggeranong,18.5,26.9,93.0,NaN,NaN,N,31.0,N,...,65.0,1009.0,1007.1,NaN,NaN,20.9,25.4,Rain,Rain,8.4
145278,26/12/16,Uluru,22.1,27.4,83.8,NaN,NaN,ENE,72.0,N,...,100.0,994.6,989.2,8.0,8.0,22.2,24.2,Rain,Rain,5.3
36960,08/03/10,WaggaWagga,18.8,25.6,110.8,NaN,10.7,NW,52.0,ENE,...,41.0,1009.2,1008.6,3.0,4.0,20.4,25.2,Rain,NoRain,6.8
128046,01/06/12,Walpole,12.4,14.6,93.2,NaN,NaN,SE,59.0,SE,...,93.0,1022.9,1022.5,NaN,NaN,14.1,13.6,Rain,Rain,2.2
79512,01/06/13,Watsonia,13.1,14.7,87.4,8.0,0.0,S,22.0,NaN,...,100.0,1013.4,1010.9,8.0,7.0,NaN,14.4,Rain,Rain,1.6
42010,06/01/16,Williamtown,18.5,19.9,225.0,NaN,0.0,S,80.0,SSW,...,90.0,1008.5,1008.8,8.0,8.0,19.2,19.4,Rain,Rain,1.4
113178,15/07/13,Witchcliffe,15.7,18.3,99.4,NaN,NaN,NW,48.0,NW,...,73.0,1012.0,1011.1,NaN,NaN,15.8,17.7,Rain,Rain,2.6
44916,25/08/15,Wollongong,12.2,15.9,192.0,NaN,NaN,SE,87.0,SW,...,83.0,1012.5,1012.1,8.0,8.0,13.6,13.5,Rain,Rain,3.7
107673,10/01/15,Woomera,18.0,24.0,66.4,NaN,0.0,SSE,50.0,S,...,73.0,1004.7,1003.3,8.0,8.0,18.6,23.2,Rain,NoRain,6.0

14. Filter out all data for the city Albury and then sort the resulting dataframe in ascending order based on the maxtemp column

In [139]:
df_Albury = df[df['location'] == 'Albury']
df_Albury = df_Albury.sort_values(by='maxtemp',ascending=True)
df_Albury

,date,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,...,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,tempdiff
2328,15/07/15,Albury,4.4,6.8,10.0,NaN,NaN,NE,30.0,S,...,93.0,1016.6,1017.1,8.0,8.0,4.7,6.4,Rain,Rain,2.4
2675,26/06/16,Albury,-1.3,7.5,0.0,NaN,NaN,ENE,15.0,NaN,...,79.0,1023.4,1019.0,8.0,NaN,2.3,7.4,NoRain,NoRain,8.8
193,12/06/09,Albury,-1.3,8.2,0.0,NaN,NaN,ESE,15.0,E,...,72.0,1025.7,1022.2,8.0,7.0,1.9,7.9,NoRain,NoRain,9.5
2673,24/06/16,Albury,6.6,8.2,4.0,NaN,NaN,W,48.0,WNW,...,85.0,1004.8,1007.6,8.0,6.0,7.0,7.5,Rain,Rain,1.6
919,08/07/11,Albury,-0.5,8.3,0.0,NaN,NaN,WNW,28.0,NaN,...,64.0,1026.0,1024.7,NaN,8.0,4.3,8.0,NoRain,Rain,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,11/09/11,Albury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,12/09/11,Albury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1529,07/05/13,Albury,3.9,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1028.6,NaN,NaN,NaN,9.8,NaN,NoRain,NaN,NaN
2031,21/09/14,Albury,3.4,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,43.0,1030.6,1027.5,NaN,NaN,12.2,18.6,NoRain,NaN,NaN
2032,22/09/14,Albury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

15. Remove all rows with missing values in the windgustdir column

In [140]:
df = df[pd.notnull(df['windgustdir'])]

16. Find the hottest day of "Perth"

In [141]:
df_Perth = df[df['location'] == 'Perth']
df_Perth = df_Perth.sort_values(by='maxtemp',ascending=False)
hottest_day= df_Perth.iloc[0]
print(hottest_day)

date             05/01/15
location            Perth
mintemp              23.2
maxtemp              44.4
rainfall              0.0
evaporation          10.6
sunshine             11.3
windgustdir            NE
windgustspeed        37.0
winddir9am             NE
winddir3pm             SW
windspeed9am         17.0
windspeed3pm         17.0
humidity9am          30.0
humidity3pm          23.0
pressure9am        1008.5
pressure3pm        1005.5
cloud9am              0.0
cloud3pm              2.0
temp9am              33.9
temp3pm              39.5
raintoday          NoRain
raintomorrow       NoRain
tempdiff             21.2
Name: 122928, dtype: object

17. Group your dataframe by location and find the average of all numerical columns per location.

In [146]:
df_mean = df.groupby('location').mean(numeric_only=True)
df_mean

,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustspeed,windspeed9am,windspeed3pm,humidity9am,humidity3pm,pressure9am,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,tempdiff
location,,,,,,,,,,,,,,,,,
Adelaide,12.571487,22.891254,1.576076,5.757117,7.742417,36.499211,9.954804,15.470774,59.716182,44.866941,1018.758665,1016.798356,NaN,NaN,16.925284,21.552038,10.319766
Albury,9.518588,22.629555,1.904552,NaN,NaN,32.977394,8.209720,14.385358,74.101198,47.907912,1018.366190,1015.752959,6.393916,5.410148,14.347304,21.361802,13.113258
AliceSprings,13.155254,29.281325,0.869484,9.042405,9.592820,40.531281,14.754603,18.098092,39.542015,24.035846,1016.684639,1012.866812,2.838528,3.242597,21.365072,28.043254,16.128423
BadgerysCreek,11.135741,24.014949,2.215406,NaN,NaN,33.600409,8.053590,13.997940,76.932530,51.426309,1018.469363,1015.657849,NaN,NaN,16.567467,22.513928,12.876525
Ballarat,7.348670,18.267930,1.706369,NaN,NaN,44.982719,19.976024,22.770792,81.801338,59.051948,1017.872715,1016.289983,5.810219,6.282246,11.658253,16.772537,10.918152
Bendigo,8.611841,21.625609,1.631586,3.835616,NaN,38.844948,12.945630,17.173173,70.579158,46.516011,1017.991296,1015.831417,4.418262,4.867384,13.850317,20.251734,13.009773
Brisbane,16.414204,26.436043,3.119424,5.406064,8.069265,28.212881,6.950508,10.993331,64.064762,53.917250,1018.252094,1015.119022,3.920025,3.886349,21.822317,24.734087,10.018130
Cairns,21.225099,29.559550,5.701852,6.244197,7.577948,38.026150,15.902649,21.907616,69.937086,61.751738,1014.152351,1011.098444,4.561036,4.441145,25.821921,27.911188,8.335563
Canberra,6.670100,20.731579,1.745920,4.134289,7.419064,40.071682,10.444228,19.082444,73.814206,46.445272,1019.003108,1016.256796,4.888889,4.802676,12.486515,19.246330,14.061479
Cobar,13.131412,25.853488,1.132655,6.751995,8.693236,36.750590,14.679717,15.143965,55.148317,33.881837,1017.994375,1015.327909,3.311223,3.861215,18.102632,24.517262,12.722076
CoffsHarbour,14.522998,23.971493,4.990985,3.912857,7.353320,39.227925,15.273139,21.186011,68.161815,62.380447,1018.245185,1015.847220,4.324651,4.500229,20.191770,22.372951,9.450322
Dartmoor,8.620518,19.696769,2.150272,3.354226,6.419215,38.898299,10.815458,17.949643,85.218739,62.439885,1018.003777,1016.512628,NaN,NaN,12.588632,18.181354,11.061622
Darwin,23.190022,32.538259,5.076454,6.315255,8.522194,40.579917,15.043561,20.848061,68.414812,51.699301,1011.911825,1008.365130,4.323268,4.296025,27.170321,31.087095,9.348236
GoldCoast,17.287324,25.713189,3.737301,NaN,NaN,42.476370,19.331962,25.831619,66.218213,62.824055,1017.981747,1015.278219,NaN,NaN,22.308973,23.712466,8.421213
Hobart,9.080883,17.858517,1.604739,3.599146,6.574842,47.530915,16.291167,19.818870,65.650316,52.974668,1014.507447,1012.941338,4.845771,4.963591,12.460271,16.166835,8.777634
Katherine,20.546272,34.915762,3.239856,7.325926,NaN,38.771465,12.100129,15.783959,63.863358,42.824897,1012.786886,1008.483840,2.587417,3.199762,26.634195,33.551130,14.394619
Launceston,7.858822,18.983062,2.016483,6.190714,NaN,35.625749,8.471547,15.555333,79.450732,57.240506,1015.647558,1013.722920,6.315716,5.719346,12.050266,17.709860,11.122877
Melbourne,11.770359,20.760489,1.874019,4.642884,6.387980,45.610255,19.091281,22.071721,67.577308,51.158990,1017.642868,1015.787500,5.311132,5.336386,14.580467,19.263822,8.992291
MelbourneAirport,9.962558,20.478958,1.456045,4.634437,6.378750,46.919172,20.244905,23.057114,70.139317,51.152429,1018.102071,1016.295090,5.246827,5.264952,14.110354,18.947027,10.516399
Mildura,10.738782,24.848202,0.945370,5.938816,8.468361,37.168775,14.000999,16.695305,64.088637,35.402000,1018.765133,1016.255929,3.384800,3.922996,15.536563,23.434266,14.109421
Moree,12.909625,26.975060,1.612936,7.639713,8.917212,39.889116,18.089170,16.832251,61.297916,35.663363,1018.329512,1014.943432,3.340373,3.961901,18.875708,25.678028,14.063720
MountGambier,8.820797,19.818882,2.078296,3.425587,6.505339,42.853030,17.496651,22.372194,75.525856,57.378986,1017.967861,1016.397587,5.518377,5.478668,13.777804,18.170476,10.999096
MountGinini,3.487122,11.506027,3.317951,NaN,NaN,46.253951,15.807078,14.979111,77.152479,70.062107,NaN,NaN,NaN,NaN,6.787454,10.086023,8.059164
Nhil,8.991959,22.394576,0.933973,NaN,NaN,42.542438,16.435227,20.960434,73.059349,44.942565,1018.537779,1016.393810,NaN,NaN,13.374091,20.863114,13.402616
NorahHead,15.346429,22.583152,3.388950,NaN,NaN,42.183051,13.866008,20.983657,74.592087,67.488079,1018.262377,1016.012033,NaN,NaN,18.463677,20.760368,7.236067
NorfolkIsland,16.868073,21.827935,3.132717,4.738062,7.013740,42.601889,20.171119,21.871414,70.779655,67.832265,1017.626928,1015.886703,5.025508,4.849725,19.777492,20.471178,4.961323
Nuriootpa,9.404508,21.751250,1.380203,5.098451,7.673709,40.681081,14.239513,18.161072,66.731707,45.364530,1018.870118,1016.746479,4.682299,4.875965,14.886270,20.358917,12.363729
PearceRAAF,12.295443,26.052760,1.691525,NaN,8.805317,43.579958,16.044787,20.362299,60.854043,42.120575,1017.600490,1015.087272,3.864047,4.047118,18.851784,24.493833,13.740498
Penrith,12.537888,24.733782,2.176233,NaN,NaN,31.807330,6.345997,11.967938,75.822859,49.006518,NaN,NaN,NaN,NaN,16.952557,23.329386,12.196018
Perth,12.921769,25.037402,1.905144,5.606527,8.786616,34.882999,10.697302,14.516939,62.677572,46.906004,1017.778820,1015.412923,3.381984,3.467337,18.574122,23.463331,12.114120
PerthAirport,12.593723,25.541714,1.744988,5.671168,8.796114,44.201822,17.760297,21.283592,58.761390,41.927414,1017.851992,1015.332917,3.379264,3.451504,18.792845,24.092944,12.947992
Portland,9.586485,18.047209,2.528629,3.416822,6.495462,42.059852,16.316852,20.769179,78.741715,65.988855,1017.709622,1016.641734,6.340086,6.075295,13.189276,16.501621,8.458072
Richmond,11.333866,24.455586,2.130970,5.247180,NaN,34.872290,7.016769,14.875299,76.874355,49.002065,1018.695907,1015.626298,6.249169,5.509499,16.551231,23.124692,13.112857
Sale,8.595363,20.321583,1.523612,3.825179,6.689749,42.479777,14.335311,22.307853,78.699895,56.201893,1017.723214,1015.801296,5.329070,5.081528,13.464759,18.818940,11.726220
SalmonGums,9.376693,24.288645,1.037027,NaN,NaN,39.748372,16.293269,17.314452,62.845520,40.778922,NaN,NaN,NaN,NaN,17.080398,22.708857,14.923624
Sydney,15.062213,23.292758,3.477445,5.317841,7.194377,41.757589,15.265740,19.739809,67.602704,54.291630,1018.302441,1015.980697,4.233523,4.184912,18.065421,21.748349,8.230542
SydneyAirport,14.893845,23.394050,2.984631,5.268154,7.193578,47.234280,18.559689,25.773081,64.735453,53.872376,1018.394002,1015.995533,4.279282,4.276200,18.550085,21.785188,8.498783
Townsville,20.412931,29.361485,3.455083,7.198736,8.465554,38.840570,15.233831,24.259529,63.931720,57.387140,1015.166788,1011.906563,4.290628,4.008727,25.632847,27.765462,8.949702
Tuggeranong,7.235581,20.771295,2.165203,NaN,NaN,35.215883,7.641560,14.882590,72.797447,47.124916,1018.525386,1015.670338,NaN,NaN,12.571045,19.438480,13.538731
Uluru,14.399533,30.389633,0.714555,NaN,NaN,41.268373,17.610928,16.986868,42.254785,23.838477,1017.145855,1013.345502,5.567568,4.832911,20.996568,29.071832,16.021281
WaggaWagga,9.628212,23.046863,1.711737,5.191840,8.208085,36.648105,12.881248,16.207648,67.833781,42.575310,1018.490876,1015.837538,3.857505,4.191952,14.940054,21.766152,13.418651
Walpole,11.837917,20.491127,2.865308,NaN,NaN,39.829640,13.924143,17.231809,76.170766,66.325710,1017.869830,1016.228933,NaN,NaN,15.944822,18.591719,8.660202
Watsonia,10.115729,20.858445,1.842159,4.631863,6.369438,38.059219,9.922585,15.199260,78.364435,54.779946,1018.057523,1016.112483,5.246972,5.266577,13.748276,19.363694,10.739744
Williamtown,12.774443,23.985346,3.621076,6.786268,7.139060,41.681518,16.419861,22.242688,71.920153,54.057511,1018.477119,1015.989892,4.711505,4.493398,18.068780,22.475279,11.210689
Witchcliffe,10.786932,21.685407,2.910366,NaN,NaN,40.083025,13.959946,19.168124,71.386637,57.826103,1018.385302,1016.727340,NaN,NaN,16.550151,19.806052,10.895081
Wollongong,14.919289,21.445166,3.611757,NaN,NaN,45.690842,16.637222,21.960685,67.649158,65.139832,1018.152821,1016.063471,6.219880,5.857854,18.173266,19.915692,6.521872
Woomera,13.410819,26.639327,0.496816,10.200118,9.042980,44.156566,20.098720,20.707786,53.012175,28.356876,1018.568959,1015.908570,2.528891,2.897103,17.974806,25.244879,13.222076